### ISSUE TITLE
Developer doc improvements related to local vagrant instance usage

### ISSUE THREAD

**Issue by dandagopi** [oneops/oneops.github.io#127]
@mosabua 

this is more  gear towards to developers,  i am listing few of them here. if you need more I can happy to chat with you some of my thoughts.

1. How to access CMS/User database from HOST system to vagrant 
2.how to get the UI code latest, currently Local vagrant UI and production UI is way off.
3.how to refresh the UI from vagrant
4. how to uninstall circuit model sync from CMS database. 

thanks
Gopi

**Comment by mosabua** [comment]
Those would all be very useful separate topics for the developer section. Specifically the core development section. It is very thin at the moment and anything you can write up in a doc would be useful. Just create a branch and write it up as a PR with a file in the core-development folder.

http://oneops.com/developer/core-development/index.html

We probably need separate details about ui development and other aspects.

Circuit (and pack and so on development) on the other hand belongs in the content development section.

**Comment by mosabua** [comment]
The content development section contains more stuff but is still a loose collection of documents with no proper structure. I still need to work on that but any help there would be GREAT.

http://oneops.com/developer/content-development/index.html
