### ISSUE TITLE
Doc and blog post about boo and boosh

### ISSUE THREAD

**Issue by mosabua** [oneops/oneops.github.io#143]
https://github.com/oneops/boosh

https://github.com/oneops/boo

Discussed with @tobrien and we are going to add it to the user section and mention on the dev section.

**Comment by dgutierrez-walmart** [comment]
Some grist for the doc mill: 
This is a quick summary of most of the pertinent references to boo and boo usage 
that I have found to date, which if compiled into a single boo reference would make 
for decent boo user documentation: 

----------------
References: 

Good end user document:
https://confluence.walmart.com/pages/viewpage.action?pageId=175291370

Excellent sample profiles with advanced variable use: 
https://gecgithub01.walmart.com/LabsBFD/bfd-photon-templates

The basic demo: 
https://gecgithub01.walmart.com/devtools/boo-demo

An excellent sample using roles: 
https://gecgithub01.walmart.com/devtools/looper-master-role/blob/master/tests/boo_template_master.yml

----------------
The missing doc

Problem: How do I find the proper naming for Oneops cofiguration elements? 

Solution: Follow the procedure below to learn how to find the json naming of config elements. 

If you are developing a Boo profile, and cannot find any sample or documentation
for the configuration elements you are trying to create/deploy through Boo, then you will 
need to access the OneOps GUI to find your references. If you know of an existing Assembly
containing the configuration elements you are trying to code into your profile, then 
open that Assembly in the GUI, drill down to the bottom of the element you are
interested in. For example, we will use a hypothetical Assembly that has a download 
element we want to encode. So we open the assembly, drill down: 

assembly->design->platform->download-<NAME>->Download-<INSTANCE-ID>

This will give you a URL like: 

https://oneops.prod.walmart.com/devtools/assemblies/187820466/design/platforms/198821688/components/199364337/edit

To see all the json elements associated with this configuration item, edit the URL to be like: 
https://oneops.prod.walmart.com/devtools/assemblies/187820466/design/platforms/198821688/components/199364337.json

This will now display all the json element associated with this configuration item, for example: 

{

    "rfcId": 0,
    "releaseId": 0,
    "ciId": 199364337,
    "nsPath": "/devtools/sonar-looper/_design/SonarQubeL",
    "ciClassName": "catalog.oneops.1.Download",
    "impl": null,
    "ciName": "download-sonar-plugin",
    "ciGoid": "198821687-30819-199364337",
    "ciState": "default",
    "rfcAction": null,
    "releaseType": null,
    "createdBy": "arangas",
    "updatedBy": null,
    "rfcCreatedBy": null,
    "rfcUpdatedBy": null,
    "execOrder": 0,
    "lastAppliedRfcId": 414639676,
    "comments": "",
    "isActiveInRelease": false,
    "rfcCreated": null,
    "rfcUpdated": null,
    "created": 1488644822362,
    "updated": 1488644822362,
    "hint": null,
    "ciAttributes": {
        "headers": "",
        "path": "/tmp/sonar-plugins-5.6.6.tar",
        "basic_auth_password": "--ENCRYPTED--",
        "basic_auth_user": "",
        "checksum": "",
        "source": " http://gec-maven-nexus.walmart.com/nexus/service/local/repositories/thirdparty/content/org/walmart/sonar/sonar-plugins/5.6.6/sonar-plugins-5.6.6.tar",
        "post_download_exec_cmd": "cd /etc/sonarqube-5.6.6/extensions/plugins/ ; sudo tar -xvf /tmp/sonar-plugins-5.6.6.tar; sh /etc/sonarqube-5.6.6/bin/linux-x86-64/sonar.sh restart;"
    },

It is the "ciAttributes": data we are after, in this case we now can encode this in our
Boo profile, where these json elements: 

    "ciAttributes": {
        "headers": "",
        "path": "/tmp/sonar-plugins-5.6.6.tar",
        "basic_auth_password": "--ENCRYPTED--",
        "basic_auth_user": "",
        "checksum": "",
        "source": " https://gec-maven-nexus.walmart.com/nexus/service/local/repositories/thirdparty /content/org/walmart/sonar/sonar-plugins/5.6.6/sonar-plugins-5.6.6.tar",
        "post_download_exec_cmd": "cd /etc/sonarqube-5.6.6/extensions/plugins/ ; sudo tar -xvf /tmp/sonar-plugins-5.6.6.tar; sh /etc/sonarqube-5.6.6/bin/linux-x86-64/sonar.sh restart;"

Becomes this Boo profile encoding: 

        download-sonar-plugin:
          source: 'https://gec-maven-nexus.walmart.com/nexus/service/local/repositories/thirdparty
/content/org/walmart/sonar/sonar-plugins/5.6.6/sonar-plugins-5.6.6.tar'
          basic_auth_user: ''
          basic_auth_password: ''
          headers: ''
          checksum: ''
          path: '/tmp/sonar-plugins-5.6.6.tar'
          post_download_exec_cmd: '{"cd /etc/sonarqube-5.6.6/extensions/plugins/ ; sudo tar -xvf /
tmp/sonar-plugins-5.6.6.tar; sh /etc/sonarqube-5.6.6/bin/linux-x86-64/sonar.sh restart;"}'


-------------------
end
