### ISSUE TITLE
formatting difference between .md file and actual pages

### ISSUE THREAD

**Issue by khushbulohia** [oneops/oneops.github.io#22]
There are some differences between load.md and load.html generated here
https://github.com/oneops/oneops.github.io/blob/master/user/references/load.md
http://oneops.com/user/references/load.html

Some example of differences:
1) Therefore the design yaml/json file generated by Extract will explicitly include:
below this line are bullet point in .md not in final page

2) curl example in .md are in grey box, on html these are highlighted in red color

**Comment by mosabua** [comment]
Found a bunch more markdown syntax errors and fixed them. @khushbulohia had a look and all is as desired now.
