### ISSUE TITLE
Confirm or remove stackoverflow

### ISSUE THREAD

**Issue by mosabua** [oneops/oneops.github.io#23]
This page http://oneops.com/contribute.html mentions the oneops stackoverflow tag and usage. However there are no questions or answers or even a tag wiki or so on stackoverflow. Should this be removed on the website or is stackoverflow usage planned. If so.. I got enough cred to create a tag and tagwiki. Wdyt @vitaliyzinchenko .. please also socialize my question with whoever appropriate.

**Comment by mosabua** [comment]
Also is the sign up URL for slack really correct on this page? https://stackstorm.typeform.com/to/K76GRP ?

**Comment by jvanzyl** [comment]
I think @kfilipovski has the new signup url that makes it really easy.

**Comment by mosabua** [comment]
Similar problem exists on http://oneops.com/about.html

**Comment by mosabua** [comment]
I am dealing with the slack sign up separately via email
