### ISSUE TITLE
Load content page still wrong URL in search

### ISSUE THREAD

**Issue by mosabua** [oneops/oneops.github.io#25]
Found in the admin section. Reported by @jksgit in https://github.com/oneops/oneops.github.io/issues/4 

The correct link for that page can be found via http://oneops.com/admin/howto/index.html and is http://oneops.com/admin/howto/load-content-model-images.html

**Comment by mosabua** [comment]
I updated the generation of the searchmap.json to improve layout and ensure its valid JSON in mist/all cases. Still having issues with the search index  .. I will debug this a bit more but might end up having to reach out to the oneops team to get this improved.

**Comment by jksgit** [comment]
Relative search path seems to be landing on valid url. But direct search is giving me http://oneops.com/admin/howto/load-content.html which is broken.

**Comment by mosabua** [comment]
What do you mean by relative search path vs direct search @jksgit ? From what I can tell most links in the search boxes drop down still use the invalid #links and so the index is definitely stale. I would like to completely wipe and re-establish is from scratch. Maybe even do that with each deployment. I will have to check out the search system more in detail...

**Comment by jksgit** [comment]
Yeah thats what i meant . Thanks

**Comment by mosabua** [comment]
I had a debugging and trouble shooting session with @gauravlall and we have a plan going forward.

**Comment by mosabua** [comment]
Its working now. I sent an email to a few stakeholders and I will document this more in the readme. At  least the urgency of the broken results is now gone. Going to proceed with streamlining and fixing and close after.

**Comment by mosabua** [comment]
Added doc to readme and scripts in scripts/elasticsearch
