### ISSUE TITLE
https://oneops.github.io/ broken links

### ISSUE THREAD

**Issue by kosmoit** [oneops/oneops.github.io#3]
All links from the main page oneoops.github.io are going to page cannot be found.  

![image](https://cloud.githubusercontent.com/assets/18224472/20350308/0538a3b6-abd4-11e6-8f01-a9c2dd805998.png)

**Comment by mosabua** [comment]
This should all work now. Please file specific further issues if you find anything else. We are working on it at the moment tracking it all down.

**Comment by mosabua** [comment]
Thanks @kosmoit for filing. If you find anything else please create another issue. I am closing this specific one cc@aloney
