### ISSUE TITLE
Scroll to top of page button

### ISSUE THREAD

**Issue by mosabua** [oneops/oneops.github.io#9]
The looper site has a back to top image in the bottom right corner that shows up as soon as the user scrolls below. The oneops site has a LOT of those long pages and they suffer from this usability issue. I think adding this button like in the looper site would be a great first step.

This is the HTML that is inserted and that you can see e.g. on the Flows page. 

```
<div id="topcontrol" title="Scroll Back to Top" style="position: fixed; bottom: 5px; right: 5px; opacity: 0; cursor: pointer;"><img src="/assets/img/up.png" style="width:51px; height:42px"></div>
```

**Comment by mosabua** [comment]
Turns out this is done by the back-to-top plugin/js.

**Comment by mosabua** [comment]
Any objection if we add this @aliloney ? Or is there some better way with the stuff we already use?

**Comment by mosabua** [comment]
Also if we pull that in .. should the js go in the plugins folder?

**Comment by aliloney** [comment]
No objection, I can add this in. Yes, I think the plugins folder is the best spot for it.

**Comment by mosabua** [comment]
Alright .. I assigned it to you .. feel free to push to master when you are done with that..

**Comment by aliloney** [comment]
Pushed to master
